### ISSUE TITLE
UnhandledPromiseRejectionWarning: no such file or directory, open 'make'

### ISSUE THREAD

**Issue by stoeffel** [gren-lang/example-projects#12]
Is this a known issue when running the examples? 
I'm getting this no matter which example I'm running.
## Error
```
╭───example-projects ──────────────────────────────────────────────────────────────────────────────────────────── main   ─┤
╰──┤  make cat
Compiling cat
(node:20747) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'make'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at /Users/stoeffel/src/gren-lang/example-projects/node_modules/gren/src/cli.js:89:25
    at Object.<anonymous> (/Users/stoeffel/src/gren-lang/example-projects/node_modules/gren/src/cli.js:110:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20747) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20747) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

## Node version:

```
╭───example-projects ──────────────────────────────────────────────────────────────────────────────────────────── main   ─┤
╰──┤  node --version
v14.20.0
```

**Comment by robinheghan** [comment]
Would you mind testing with Node v18, which is the current LTS version of Node?

**Comment by stoeffel** [comment]
Getting the same error:

```
╭───example-projects ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── main ﬒  ─┤
╰──┤  node --version
v18.12.1
╭───example-projects ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── main ﬒  ─┤
╰──┤  make cat
Compiling cat
node:fs:600
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'make'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at /Users/stoeffel/src/gren-lang/example-projects/node_modules/gren/src/cli.js:89:25
    at Object.<anonymous> (/Users/stoeffel/src/gren-lang/example-projects/node_modules/gren/src/cli.js:110:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'make'
}

Node.js v18.12.1
make: *** [Makefile:35: cat] Error 1
```

**Comment by stoeffel** [comment]
Nope, I was wrong. Deleted `node_modules` after upgrading and now things are okay 👍
